### ISSUE TITLE
Add endpoint for upload cover image

### ISSUE THREAD

**Issue by analyticsjam** [steinitzu/spotify-api#2]
Would it be possible for you to add support for the endpoint to upload a custom cover image?  It was added since the last time you updated the repo.  I tried to create a merge request but wasn't able to get it working.

Thanks for the repo, it's working great.

https://developer.spotify.com/documentation/web-api/reference/playlists/upload-custom-playlist-cover/

**Comment by vaibhavhrt** [comment]
@steinitzu I will be working on it. I will open a PR but if you are no longer maintaining a this project, I will publish my fork to pypi and maintain that.

**Comment by steinitzu** [comment]
Hi guys

Sorry for the delay. I'm not actively maintaining this project anymore, but @vaibhavhrt  I'll happily take a PR for this and try to release asap.
Let me know if any questions for implementing it.

**Comment by vaibhavhrt** [comment]
Thanks, I don't wanna have to maintain a fork anyway. I will let you know if I need any help.

**Comment by vaibhavhrt** [comment]
@steinitzu is it ok if I put simple flask app example in the example folder of the repo. I had to create a flask app for testing anyway. If you don't want it I will not commit it in git.
